services:
  keycloak-w:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABSE: keycloak
      KC_DB_SCHEMA: public
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - "postgres_keycloak_demo"
    networks:
      - keycloak_demo_dev_network

  postgres_keycloak_demo:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
      - POSTGRES_DB=keycloak
    healthcheck:
      test: "exit 0"
    ports:
      - "5434:5432"
    volumes:
      - pgdata_keycloak_demo:/var/lib/postgresql/data
    networks:
      - keycloak_demo_dev_network

volumes:
  pgdata_keycloak_demo:

networks:
  keycloak_demo_dev_network:
    driver: bridge